### ISSUE TITLE
Second level namespace is not clickable

### ISSUE THREAD

**Issue by drprincenanda** [dive2Pro/roam-hierarchy#1]
Hello the first namespace works fine Example:
project/ ABC 
in this if I click project then it shows the nice hierarchy however 

project/personal/XYZ
in this personal is not clickable while project is clickable and shows the hierarchy

**Comment by dive2Pro** [comment]
Thanks for the report, it looks like a problem with roamAlphaAPI.  
I've reported it to roamteam

**Comment by dive2Pro** [comment]
the problem is sovled. you can update roam to see it
