### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by CCapra** [dive2Pro/roam-hierarchy#2]
Grateful for this extension - it's a step in the right direction re: namespaces - thanks!

It would be great if the hierarchy could be ordered alphabetically (and maybe by recent change or other chronological order)
It would also be great if the hierarchy of a page could be opened in the right side-panel.

**Comment by dive2Pro** [comment]
Thanks for the feedback, I've pushed the next version for review, so
1. I will look into it before the next version is merged, and see if I can update it together.
2. you can `shift + click` to open it in the right sidebar (if the page is already created.  in the next version you don't need to create the page before opening it).

**Comment by dive2Pro** [comment]
@CCapra new version updated. please try to update and feel free to leave your feedback
