### ISSUE TITLE
Hierarchy on Daily Notes log

### ISSUE THREAD

**Issue by fbgallet** [dive2Pro/roam-hierarchy#3]
Hi,
hierarchy appears in the Daily Notes log, under the first day, which does not make sense.

![image](https://user-images.githubusercontent.com/74436347/222894885-bf274db3-631e-44bd-8f52-eb4022d4ab78.png)

**Comment by dive2Pro** [comment]
Hello, @fbgallet. The fixed code has been merged. Can you please confirm if the issue has been resolved?

**Comment by fbgallet** [comment]
Thanks @dive2Pro , it's fixed!
