### ISSUE TITLE
Is it possible to make hierarchy display more like a true hierarchy?

### ISSUE THREAD

**Issue by owliatian** [dive2Pro/roam-hierarchy#4]
For now it's handled similarly to logseq in page which is like for each child page display all parent in single line, is it possible to display in a true outliner? or maybe like {{namespace: }} in logseq?

**Comment by dive2Pro** [comment]
What is your use case, can you give an example?

**Comment by owliatian** [comment]
It maybe just a design choice, for example:

if I have two namespaces called `[[a/b/c/d]]` and `[[a/e/f]]` , on page `[[a]]` , the hierarchy will display like this:

![image](https://user-images.githubusercontent.com/43448080/224352050-be6f470a-8391-425f-a64f-5b48eb03695c.png)

this can work but feel a bit redundant:

![image](https://user-images.githubusercontent.com/43448080/224353440-69687791-05fd-4836-8f25-79b991b76ff9.png)

If we want to describe the page's memberships,  `a-b-c-d` and `a-e-f` should be enough.

However, now I want to add new namespace called `[[a/e/g]]`, in this case we will have to add a new line to express its membership:

![image](https://user-images.githubusercontent.com/43448080/224360512-ed4288f6-990b-4d12-9926-84ebeeba0d35.png)

pretty well but I think the `[[a]] / [[e]]` doesn't need to display twice, with the increase of this type of namespace, the hierarchy will become noisier which will decrease clarity.

So these problems can be solved by just using the outline to display page's memberships:

![image](https://user-images.githubusercontent.com/43448080/224365500-8665d86b-d52e-4069-b25a-40705350957e.png)

Or like:

![image](https://user-images.githubusercontent.com/43448080/224367881-aa2f6968-dcd0-49b7-ac71-8ff14f2f0401.png)

Overall, this maybe my personal preference so what I'm wondering is whether it's possible to achieve this in Roam?

**Comment by dive2Pro** [comment]
Do you know that there is a sorting function here that arranges items in alphabetical order? Like this:
![image](https://user-images.githubusercontent.com/23192045/225525713-da94b4af-6dc2-4ac9-90db-f6ef44de78de.png)

**Comment by owliatian** [comment]
I didn't know that before but it doesn't matter anymore since I switched tools, anyway thanks for your help!
