### ISSUE TITLE
Conflict between hierarchy and embedded queries on a page

### ISSUE THREAD

**Issue by allenhutchison** [dive2Pro/roam-hierarchy#5]
If you add an embedded query in a page that has a hierarchy, the hierarchy will show up inside the UI for the TODO instead of at the bottom of the page. I've reproduced this on a test graph with no data and a toy hierarch and no plugins except for roa-hierarchy.

<img width="1350" alt="Screenshot 2023-05-11 at 9 26 02 AM" src="https://github.com/dive2Pro/roam-hierarchy/assets/3849061/21cc6aeb-ed2e-4965-84d1-5138f609c14b">

**Comment by dive2Pro** [comment]
Sorry for the delay in responding. The issue will be addressed and fixed in the next version  Roam-Research/roam-depot#768
