### ISSUE TITLE
Redundant date information

### ISSUE THREAD

**Issue by abbyyhhpp** [dive2Pro/roam-hierarchy#8]
![image](https://github.com/dive2Pro/roam-hierarchy/assets/134356873/14792ab1-5730-4bf0-b9c3-766b8fda48cf)

**Comment by dive2Pro** [comment]
The displayed backlinks have an effect similar to **embed-path**, so that you can check its parent block when browsing the hierarchy.

Perhaps I can add control options for it in the settings.
